### ISSUE TITLE
Have you any plans to extend nsparse?

### ISSUE THREAD

**Issue by gsvgit** [EBD-CREST/nsparse#3]
What about 
- matrices summation: A + B
- a general expression of form A + (B * C) or more general.

Basically, it would be great to have (+) operation for your matrix format.

**Comment by YusukeNagasaka** [comment]
Thank you for your interest.

Do you assume CSR format? For now, I have no plan about extending our work to matrix summation because the matrix summation itself is also challenging problem to tune.

Of course, I know combining multiple kernels is more efficient, but it would be better to use vendor tuned matrix summation kernel such as cuSPARSE besides nsparse in the current situation.

**Comment by gsvgit** [comment]
Thank you! 

Is matrix representation format in nsparse fully compatible with CSR in cuSPARSE? Or any sort of conversion may be required?

**Comment by YusukeNagasaka** [comment]
Yes. You can directory access "row pointer", "column indices" and "values" of CSR class in nsparse, so no conversion is not required.

**Comment by gsvgit** [comment]
Great!
