### ISSUE TITLE
race condition in hashmap entry allocation

### ISSUE THREAD

**Issue by dabeschte** [EBD-CREST/nsparse#4]
I guess I found a race condition in the main loop of all HashSpGEMM methods.
The `if (old == -1)` should be replaced by `if (old == 1 || old == key)`, because a different thread could have already reserved this entry and the current thread reserves a new entry at a different location.

Please correct me if I'm wrong ;-)

```
while (1) {
    if (id_table[adr] == key) {
        atomicAdd(value_table + adr, aval * bval);
        break;
    }
    else if (id_table[adr] == -1) {
        old = atomicCAS(id_table + adr, -1, key);
        if (old == -1) {
            atomicAdd(value_table + adr, aval * bval);
            break;
        }
    }
    else {
        hash = (hash + 1) & ((TS_N_P) - 1);
        adr = soffset + hash;
    }
}
```

**Comment by YusukeNagasaka** [comment]
I think there is no race condition, but your suggestion can make the code more efficient.

When multiple threads enter `if (id_table[adr] == -1` and one thread changes the status of `id_table[adr]` to key at first, the other threads get `old = key` from atomicCAS function. In this case, the other threads continue executing while loop. Since adr is not changed, atomicAdd is correctly executed in `if (id_table[adr] == key) of next iteration.

However, the current implementation requires another next loop iteration. Your suggestion `if (old == 1 || old == key)` can reduce the iterations.

Thank you!

**Comment by dabeschte** [comment]
Oh, that is correct. Thank you for the explanation!
